### ISSUE TITLE
Hello...

### ISSUE THREAD

**Issue by ghost** [nihilus/ScyllaHide#5]
Themida -> anti-debug

https://github.com/fishstiqz/mitigationview
Route : 

1. some code calls GetCurrentProcess.
2. if it returns -1, it calls NtQueryInformationProcess with 0x34 (52u).
3. NtQueryInformationProcess returns 0 (Success).
4. Then it calls GetProcessMitigationPolicy that returns 0.
5. After call OutputDebugStringA , it show me the themida message.
6. Stills receiving error maybe because i don't escaped from SSH

Route 2 : 

1. some code calls GetCurrentProcess (at first of file, the first time it's called is from the themida trap).
2. if it returns 0, it calls NtQueryInformationProcess with 0x34 (52u) (changing from -1 to 0 is to avoid UnhandledException).
3. NtQueryInformationProcess returns 0xC0000008. (INVALID_HANDLE_VALUE). Then i change it to 0
4. Then it calls GetProcessMitigationPolicy that returns 1.
5. After all steps, it no more calls OutputDebugStringA.
6. Stills receiving error maybe because i don't escaped from SSH

![image](https://cloud.githubusercontent.com/assets/12580473/25717284/5b8783de-30d8-11e7-83f1-f82cd25498d4.png)
![image](https://cloud.githubusercontent.com/assets/12580473/25718296/e56ebd4e-30db-11e7-8938-d0d0527cb3f6.png)

Notice that in this Themida version the calls of NTDLL . ^^ ntdll.Dialog and ntdll.Defproc. I can't defeat with scylla plugin. 

About 0x34 in NtQueryInformationProcess :

"This information class is for kernel-mode use only. If executing for a user-mode request, the function fails, returning STATUS_PRIVILEGE_NOT_HELD."

Is it a type of warning that is show only there is a debugger ? 
Well, sending this to olly will crash it 

then it's a protection to ring0 debuggs ?

Themida should call outputdebugstring after my edit, but it doesn't call and i believe i've escaped from the trap. but Scylla can away this . but i'm just pointing one more thing. 

then i got 

https://msdn.microsoft.com/pt-br/library/windows/desktop/hh871471(v=vs.85).aspx

http://pferrie.host22.com/papers/antidebug.pdf

I don't know why i have done this, and i don't know if i've escaped from the trap 'cause im falling into 0xC0000142 about my file edition;
http://www.geoffchappell.com/studies/windows/km/ntoskrnl/api/ex/sysinfo/set.htm

https://github.com/rrbranco/blackhat2012/blob/master/Csrc/fcall_examples/fcall_examples/fcall_examples.cpp

**Comment by nihilus** [comment]
As one who provides updated binaries for IDA Pro users this is not a problem I will fix.
