### ISSUE TITLE
"Use x64dbg to debug this process!" message on attach

### ISSUE THREAD

**Issue by khang06** [nihilus/ScyllaHide#6]
When I start a process in x32dbg and try using ScyllaHide, it instantly terminates the process after attempting to hook the process. It happens on all executables, packed or not.
![image](https://user-images.githubusercontent.com/11239786/30136107-74feb17e-932b-11e7-910a-43fe6f004afa.png)
I'm not sure if I'm doing anything wrong here.

Windows 10
Latest x64dbg

**Comment by khang06** [comment]
I just realized that this repo is dead.

**Comment by nihilus** [comment]
Well, I am a person short of time... Doesnt mean a repo os dead. Actually Ivent got a notice in the first place that you write 2 days ago.

**Comment by khang06** [comment]
oooh. I thought the x64dbg repo was where all the development was at. Sorry.
